### ISSUE TITLE
Problems with Android 10

### ISSUE THREAD

**Issue by goldenHairDafo** [pp3345/ykDroid#14]
After an update to Android 10 ykDroid stopped working. After 
the prompt to insert the yubikey nothing happens. The prompt
is still displayed, but nothing further happens. Thanks!

**Comment by pp3345** [comment]
What device? Are you using a custom ROM? Is there anything about "USB-OTG" support in your device's settings app? If so, is it disabled?

**Comment by goldenHairDafo** [comment]
Device is a Samsung Galaxy Tab S4. No custom Rom. USB-OTG I am not sure about, but I didn't change any setting.
USB-Debugging is disabled.

**Comment by pp3345** [comment]
I've now tested with two different Android 10 devices and it worked fine with both. This is likely an issue with your device. Please look again through the settings on your device for anything that looks like an option to enable USB host mode (some devices have this disabled by default).

In case you can't find anything: are you familiar with the `adb` tool?

**Comment by goldenHairDafo** [comment]
Hi,

I have looked again and I couldn't found anything in the settings. I can tell you, 
that my yubico key has both slots configured, and the first slot is configured for 
a static password. This slot still works.

I wouldn't say I'm very familiar with the adb tool, but I have used it before and I have it install
on my laptop. So how can I help? What should I do? Thank.

**Comment by goldenHairDafo** [comment]
Hi,

I have looked again and I couldn't found anything in the settings. I can tell you, 
that my yubico key has both slots configured, and the first slot is configured for 
a static password. This slot still works.

I wouldn't say I'm very familiar with the adb tool, but I have used it before and I have it install
on my laptop. So how can I help? What should I do? 

BTW. I'm not the only one with this problem. On the Google Play Store are some 
reviews with the same issue, but thanks to Google you probably can't see them 
because the are not write in English.

Thank.

**Comment by crjeder** [comment]
> After an update to Android 10 ykDroid stopped working. After
> the prompt to insert the yubikey nothing happens. The prompt
> is still displayed, but nothing further happens. Thanks!

Same here. Google Pixel 4 with stock Android 10. Yubikey Neo 4 via NFC. 
Challenge response is configured in slot 2. I don't see the option to change wich slot to use anymore. It allways takes the static password from slot 1 and enters it on cursor position in the password field.
Any help apreciated!

p. s.:
I very much honor pp3345's effort to support us users!

**Comment by pp3345** [comment]
@goldenHairDafo Okay, please try the following steps:

1. Make sure your tablet and your computer are on the same local network
2. Connect your tablet to your computer via USB
3. Make sure USB debugging is enabled and your PC is authorized (you can verify using `adb devices` that your device is properly detected)
4. Run `adb tcpip 5555` (this will tell your device to enable debugging via network instead of USB)
5. Run `adb connect <ip>:5555` where `<ip>` is your tablet's IP address (you should be able to find the address somewhere in the settings)
6. Detach your tablet from the USB cable
7. Run `adb logcat` on your computer and leave it running
8. Try to use ykDroid as you normally would
9. Stop `adb logcat` by pressing `Ctrl+C`
10. Copy the output from `adb logcat` into a text file and upload it here

Don't hesitate to ask if you have trouble with any of these steps.

@crjeder Your case seems a bit different as you are using NFC instead of USB. I am not entirely sure how the static value from slot 1 could end up in the password field. Sorry for the dumb questions but did you make sure to select the correct master key type and press the unlock button before trying to swipe your YubiKey? Do you still hear the NFC sound when setting your phone's media and ringer volumes to loud?

**Comment by goldenHairDafo** [comment]
@pp3345 so I create the log file and used gzip to pack it because the file
is rather large (10MB). Thanks again for your help

[ykDroid.log.gz](https://github.com/pp3345/ykDroid/files/5023557/ykDroid.log.gz)

BTW: Another difference with @crjeder problem is the I can select the slot.

**Comment by pp3345** [comment]
@goldenHairDafo Sadly, the log file doesn't reveal anything useful. Can you please check whether some system notification appears after plugging the YubiKey (where you can select the USB mode or perhaps something like that)? If that's not the case I'll provide you with a debug build during the next few days to track this issue down.

**Comment by goldenHairDafo** [comment]
@pp3345 So I have tried all USB modes File Transfer, Tethering, MIDI and Charging Only. No luck.

**Comment by pp3345** [comment]
@goldenHairDafo Sorry for the delay here. I've created a build of ykDroid with some more debugging information that should help us to get to the root of this issue. Please download and install it from [1], then try again the steps from https://github.com/pp3345/ykDroid/issues/14#issuecomment-668655505, and upload the log file here. Note that this is an unsigned debug build, so you will need to uninstall ykDroid first, otherwise Android won't allow you to install this one.

[1] https://dev.pp3345.net/ykdroid-31a6c6ee++-debug.apk

**Comment by dhillq1** [comment]
@pp3345

I seem to be experiencing the same problem.

My phone is a Pixel 3a on Android 10

Log attached using the supplied debug version of ykdroid.

It seems that ykdroid is not detecting the key even after insertion.

[clean.log](https://github.com/pp3345/ykDroid/files/5196531/clean.log)

**Comment by pp3345** [comment]
@dhillq1 Thanks a lot for your logs. I've played around a bit and found that I actually can reproduce the problem -- but only with my old YubiKey II, not with any newer ones. I did a lot of digging and have found the culprit. It's this commit that shipped in Android 10: [1]

The change was supposed to filter away USB hubs in order to avoid hangs in Android's USB stack. However, the checks that were introduced by the commit also match older YubiKeys by accident. So after all, this is a bug in Android itself. I've contacted the responsible Google employee, so hopefully this might get fixed in a future Android version. For now, there is nothing I can do to work around the problem, I am sorry. I recommend using a newer YubiKey if you have one.

[1] https://android.googlesource.com/platform/frameworks/base/+/e8c3a3e92c26f6ef923eb8f8ab0f9027c106be6e

**Comment by dhillq1** [comment]
Many thanks for investigating this.

@pp3345 Which type of yubikey works for you ? The one not working for me is YubiKey 5C Nano.

**Comment by goldenHairDafo** [comment]
@pp3345 Thanks for the work anyway.
I have a slightly new one laying around with Firmware Version 3.3.0 and still no luck. Could it be, that the USB-A-to-USB-C Adapter I use has anything to do with it?

**Comment by pp3345** [comment]
The ones that work for me are the YubiKey NEO, YubiKey 4 Nano, and YubiKey 5C. Together with the YubiKey II, these are all YubiKeys I own.

@dhillq1 @goldenHairDafo To check whether your YubiKeys are affected by the same issue (or if something different is going on), I'll need a dump of the USB interface descriptors:

* On Linux, just run `lsusb -v`
* On Windows, you can use this tool: https://www.uwe-sieber.de/usbtreeview_e.html (download at the bottom of the page)
Locate the YubiKey in the tree structure on the left and then copy the output from the pane on the right side

Then please attach the output here and I'll have a look.

**Comment by goldenHairDafo** [comment]
@pp3345 Here are my dumps for both YubiKey I have tested. Both with and without
USB-A-to-USB-C adapter. Create on Arch Linux with lsusb -v

[lsusb_output.zip](https://github.com/pp3345/ykDroid/files/5212961/lsusb_output.zip)

**Comment by dhillq1** [comment]
@goldenHairDafo 

Bus 001 Device 024: ID 1050:0010 Yubico.com Yubikey (v1 or v2)

    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      

> **bInterfaceClass         3 Human Interface Device**
>       **bInterfaceSubClass      1 Boot Interface Subclass**

      bInterfaceProtocol      1 Keyboard


Means it it ignored by the code in 

    private boolean isBlackListed(int clazz, int subClass) {
        // blacklist hubs
        if (clazz == UsbConstants.USB_CLASS_HUB) return true;
        // blacklist HID boot devices (mouse and keyboard)
        return clazz == UsbConstants.USB_CLASS_HID
                && subClass == UsbConstants.USB_INTERFACE_SUBCLASS_BOOT;
    }

from https://android.googlesource.com/platform/frameworks/base/+/e8c3a3e92c26f6ef923eb8f8ab0f9027c106be6e/services/usb/java/com/android/server/usb/UsbHostManager.java

Adapter should not impact these interface descriptors

**Comment by dhillq1** [comment]
@dhillq1 @goldenHairDafo My YubiKey 5C Nano has this problem truncated lsusb -v below.

Bus 020 Device 035: ID 1050:0401 Yubico.com 
Device Descriptor:

  idVendor           0x1050 Yubico.com
  idProduct          0x0401 
  bcdDevice            5.24
  iManufacturer           1 Yubico
  iProduct                2 YubiKey OTP
  Configuration Descriptor:
      (Bus Powered)
    MaxPower               30mA
    Interface Descriptor:
      **bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass**
      bInterfaceProtocol      1 Keyboard
      iInterface              0

**Comment by pp3345** [comment]
@dhillq1 @goldenHairDafo Indeed all of your YubiKeys seem to be affected, too. This is probably because your YubiKeys are OTP-only keys. For example, @goldenHairDafo's NEO identifies as `0x0110 Yubikey NEO(-N) OTP`, whereas my NEO is a `0x0116 Yubikey NEO(-N) OTP+U2F+CCID`. My NEO exposes additional interface descriptors that make it pass through Android's filter.

**Comment by dhillq1** [comment]
@pp3345 @goldenHairDafo  The issue with my Yubikey 5C nano was that I had only the OTP interface actived in yubikey manager with only expose the blocked descriptors activating them all fixed the problem by exposing additonal descriptors as you mentioned above.

@pp3345 Thank for the helping in resolving this matter and for developing ykDroid in the first place.

**Comment by goldenHairDafo** [comment]
@dhillq1 Thanks for the hint. After setting my YubiKey 3 to OTP+U2F+CCID (using `ykpersonalize -m 6`) at least this key works on Andoird 10 now.

@pp3345 Thanks again for the help and all the work!
